---
# tasks file for set_sudoers
- name: set PermitRootLogin no
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^ansible ALL='
    line: 'ansible ALL=(ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'

