---
# tasks file for install_jenkins
- name: "jenkins yum repository"
  yum_repository:
    name: jenkins
    description: "jenkins yum repo"
    baseurl: "https://pkg.jenkins.io/redhat/"
- name: "jenkins-ci.org.key installed"
  rpm_key:
    key: "http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key"
- name: "Jenkins installed"
  yum:
    name: jenkins
    state: latest
- name: "Jenkins service started"
  service:
    name: jenkins
    state: started
    enabled: yes
- name: "8080 port open"
  firewalld:
    port: 8080/tcp
    state: enabled
    permanent: yes
    immediate: yes
