---
# tasks file for selinux_disable
- name: selinux disabled
  selinux:
    state: disabled
- name: getenforce
  shell: getenforce
  register: selinux_result
- name: message
  debug: msg="You need reboot!" 
  when: selinux_result.stdout != "Disabled"


#https://qiita.com/CsFactoryitter/items/411f9a2da528b0c9dd7f
#- name: SELinuxのDisableでない場合サーバ再起動待ち
#  local_action: wait_for host={{ inventory_hostname }} port=22 delay=10
#  when: selinux_result.stdout != "Disabled"
