---
# tasks file for set_sshd_conf
- name: set PermitRootLogin no
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin\s"
    line: "PermitRootLogin no"
  notify: sshd restart
- name: set PasswordAuthentication no
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication\s"
    line: "PasswordAuthentication no"
  notify: sshd restart
- name: set PasswordAuthentication no
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^ChallengeResponseAuthentication\s"
    line: "ChallengeResponseAuthentication no"
  notify: sshd restart

