---
# tasks file for set_authorized_keys
- name: create ~/.ssh
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700
- name: send authorized keys
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
