---
# tasks file for install_mariadb
- name: yum install mariadb-server
  yum:
    name: mariadb-server
    state: latest
- name: service start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
