---
# tasks file for install_httpd
- name: yum instal httpd
  yum:
    name: httpd
    state: latest
- name: service start httpd
  service:
    name: httpd
    state: started
    enabled: yes
- name: open port 80/443
  firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - https
    - http
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
